name: Bootloader

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - 'feather_nrf52832'
          - 'feather_nrf52840'
          - 'arduino_nano_33_ble'

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Checkout Code
      uses: actions/checkout@v1
      with: |
        fetch-depth:1
        submodules: true

    - name: Install Toolchains
      run: |
        pip3 install adafruit-nrfutil uritemplate requests intelhex
        npm install --global xpm
        # 9.3.1-1.2.1 is xpack modified version which significantly increased compiled size to 6-7KB and cause flash overflow.
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@9.3.1-1.1.1
        echo `echo $HOME/.local/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin` >> $GITHUB_PATH

    - name: Build
      run: |
        make BOARD=${{ matrix.board }} all
        make BOARD=${{ matrix.board }} copy-artifact

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.board }}
        path: _bin/${{ matrix.board }}

    - name: Create Release Asset
      if: ${{ github.event_name == 'release' }}
      run: zip -jr ${{ matrix.board }}_bootloader-${{ github.event.release.tag_name }}.zip _bin/${{ matrix.board }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'release' }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.board }}_bootloader-${{ github.event.release.tag_name }}.zip
        asset_name: ${{ matrix.board }}_bootloader-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset for Self-Update
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'release' }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: _bin/${{ matrix.board }}/${{ matrix.board }}_bootloader-${{ github.event.release.tag_name }}_nosd.uf2
        asset_name: ${{ matrix.board }}_bootloader-${{ github.event.release.tag_name }}_nosd.uf2
        asset_content_type: application/x-binary
